version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: profwise-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    # Use custom config file with password authentication
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    networks:
      - profwise-network

  postgres:
    image: postgres:16-alpine
    container_name: profwise-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-profwise}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - profwise-network

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local

networks:
  profwise-network:
    driver: bridge
